-- Generated by scripts/generate-workout-plan-seed.mjs — do not edit by hand; re-run the script after JSON changes.
-- Seed: Dev's Plan + exercises + plan_days + plan_exercises (from legacy workoutPlan.json)

begin;

insert into public.plans (id, name, goal, level, days_per_week) values (
  'f889b46e-a829-5c23-b19b-20cf66ed4931'::uuid,
  'Dev''s Plan',
  'Lean muscle mass (non-bulky)',
  'Intermediate (6 months training)',
  5
) on conflict (id) do update set
  name = excluded.name,
  goal = excluded.goal,
  level = excluded.level,
  days_per_week = excluded.days_per_week;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '13fff305-1b3c-5592-8068-02ab6e566c19'::uuid,
  'Barbell Bench Press',
  'Barbell',
  'Compound',
  'Chest (pec major)',
  ARRAY['Front deltoid','Triceps'],
  'Grip just outside shoulder width. Avoid wide grip to protect shoulders.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '93fcd3fd-5290-5800-8bcc-c39d8a03575d'::uuid,
  'Incline Dumbbell Press',
  'Dumbbell',
  'Compound',
  'Upper chest (pec clavicular head)',
  ARRAY['Front deltoid','Triceps'],
  'Bench at 30-45 degrees. Upper chest key for defined look.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'e3ddcaff-533d-5e10-903f-8be26eda4772'::uuid,
  'Chest Fly Machine',
  'Machine',
  'Isolation',
  'Chest (pec major)',
  ARRAY[]::text[],
  'Slow stretch at bottom. Squeeze at top.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '350f9ab3-e54f-5607-9aa5-69d470b75c75'::uuid,
  'Dumbbell Lateral Raise',
  'Dumbbell',
  'Isolation',
  'Lateral deltoid',
  ARRAY[]::text[],
  'Lead with elbows, not wrists. Slight forward lean.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '893c6ab3-20ee-577d-a820-d3da50d26b7d'::uuid,
  'ISO Lateral Shoulder Press Machine',
  'Machine',
  'Compound',
  'Deltoids (all heads)',
  ARRAY['Triceps'],
  'Safe overhead pressing after lateral raises.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'f2edab83-ce37-5d11-a123-b6993e882909'::uuid,
  'Dumbbell Overhead Tricep Extension',
  'Dumbbell',
  'Isolation',
  'Triceps (long head)',
  ARRAY[]::text[],
  'Full stretch at bottom. Use one dumbbell overhead.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '833e4b9a-e5d6-5a59-91e5-10cbea9da999'::uuid,
  'Barbell Bent-Over Row',
  'Barbell',
  'Compound',
  'Mid back (rhomboids, traps, lats)',
  ARRAY['Biceps','Rear deltoid'],
  'Hinge at hips to 45 degrees, neutral spine. Don''t ego-lift.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'e5362472-5135-5186-b23e-1fbe56c903a0'::uuid,
  'Pull-ups / Assisted Pull-ups',
  'Bodyweight / Assisted machine',
  'Compound',
  'Latissimus dorsi',
  ARRAY['Biceps','Rear deltoid'],
  'Best lat width builder. Use assisted machine if needed.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'bdb953c0-f50b-5a17-83c1-0621d7e800d1'::uuid,
  'Front Facing Lat Pull Down Machine',
  'Machine',
  'Compound',
  'Latissimus dorsi',
  ARRAY['Biceps'],
  'Backup vertical pull. Wide grip, pull to upper chest.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '7d24759e-0b4d-58e7-8c62-0882fdbcde77'::uuid,
  'Seated Cable Row / T-Bar Row Machine',
  'Cable or Machine',
  'Compound',
  'Mid back (rhomboids, lower traps)',
  ARRAY['Biceps'],
  'Squeeze shoulder blades at peak contraction.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '49a8bb50-ee5c-58f4-a0ce-68fd8b84d66d'::uuid,
  'Dumbbell Bicep Curl',
  'Dumbbell',
  'Isolation',
  'Biceps brachii',
  ARRAY[]::text[],
  'Supinate (twist palm up) at the top for full contraction.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '6d1805f3-11a5-5523-9477-980288e4cca1'::uuid,
  'Hammer Curl',
  'Dumbbell',
  'Isolation',
  'Brachialis',
  ARRAY['Brachioradialis'],
  'Neutral grip (thumbs up). Adds arm thickness.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'fa090008-e840-5fb3-9069-68cf6cbd24f6'::uuid,
  'Barbell Back Squat',
  'Barbell',
  'Compound',
  'Quadriceps, Glutes',
  ARRAY['Hamstrings','Core','Erectors'],
  'Squat to parallel or slightly below.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '80832e73-7e2f-5626-bef4-d48bd7e10f0c'::uuid,
  'Romanian Deadlift',
  'Barbell or Dumbbell',
  'Compound',
  'Hamstrings, Glutes',
  ARRAY['Erector spinae'],
  'Hinge, don''t squat. Feel stretch in hamstrings. Slight knee bend.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '63ac6a25-3b5c-5ba0-8584-d505ff4e5fd3'::uuid,
  'Hack Squat Machine',
  'Machine',
  'Compound',
  'Quadriceps',
  ARRAY['Glutes'],
  'Deeper squat pattern, less spinal load.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '43789256-efe7-5941-8c94-d9aa225551d6'::uuid,
  'Leg Curl Machine',
  'Machine',
  'Isolation',
  'Hamstrings',
  ARRAY[]::text[],
  'Balances quad dominance. Slow eccentric phase.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'a2bb7e35-7870-509e-b063-d2f879ec4d65'::uuid,
  'Hip Thruster Machine',
  'Machine',
  'Isolation',
  'Gluteus maximus',
  ARRAY['Hamstrings'],
  'Full hip extension at top. Squeeze hard at peak.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '66c637ea-103f-53ce-8d63-d186f2924674'::uuid,
  'Seated Calf Raises Machine',
  'Machine',
  'Isolation',
  'Soleus',
  ARRAY[]::text[],
  'Full stretch at bottom. Bent knee targets soleus.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'ecf772fb-24ee-593c-b45d-d6a07f86b680'::uuid,
  'Hanging Leg Raise',
  'Pull-up bar (Bodyweight)',
  'Compound',
  'Lower abs, Hip flexors',
  ARRAY['Upper abs'],
  'Control the swing. Lower legs slowly.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'db267787-ecc0-57c6-83eb-81977a39a4f8'::uuid,
  'Abdominal Crunch Machine',
  'Machine',
  'Isolation',
  'Rectus abdominis (upper)',
  ARRAY[]::text[],
  'Pause and squeeze at peak contraction.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'f0c4e5ea-88b0-5675-ac8d-5bfba4a48deb'::uuid,
  'Plank',
  'Bodyweight',
  'Isometric',
  'Transverse abdominis (deep core)',
  ARRAY['Obliques','Glutes'],
  'Neutral spine — don''t let hips sag or rise.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'caa86797-74a2-59a8-b1d7-b1e97acd2f8c'::uuid,
  'Dumbbell Side Bend',
  'Dumbbell',
  'Isolation',
  'Obliques',
  ARRAY[]::text[],
  'Hold dumbbell in one hand. Directly targets love handles.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '1015ce0b-382e-517a-8014-89f6eef628f3'::uuid,
  'Back Extension Machine',
  'Machine',
  'Isolation',
  'Erector spinae',
  ARRAY['Glutes'],
  'Pairs with crunches for spine balance.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '460df74a-a97a-5df5-9f84-3415da3821c1'::uuid,
  'Deadlift',
  'Barbell',
  'Compound',
  'Full posterior chain (hamstrings, glutes, erectors)',
  ARRAY['Traps','Lats','Core','Quads'],
  'Most complete full-body compound. Learn form carefully before loading heavy.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '4a902087-2e5a-5afd-895b-c2c376d65723'::uuid,
  'Dumbbell Shoulder Press',
  'Dumbbell',
  'Compound',
  'Deltoids (all heads)',
  ARRAY['Triceps'],
  'Full range of motion. Neutral or pronated grip.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'd90ffdd1-0018-5cad-8beb-7798032064c6'::uuid,
  'Dumbbell Incline Row',
  'Dumbbell',
  'Compound',
  'Mid back (rhomboids, lower traps)',
  ARRAY['Biceps'],
  'Chest-supported on incline bench. Zero lower back stress.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  'ecaf1ca5-e0ec-5332-b66c-c34c5b7d0460'::uuid,
  'Leg Press Machine',
  'Machine',
  'Compound',
  'Quadriceps, Glutes',
  ARRAY['Hamstrings'],
  'Don''t lock knees at top.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.exercises (id, name, equipment, type, muscle_primary, muscle_secondary, notes) values (
  '0d5b115a-cbb6-5194-810a-15f6c039bc1b'::uuid,
  'Dumbbell Tricep Kickback',
  'Dumbbell',
  'Isolation',
  'Triceps (lateral and medial head)',
  ARRAY[]::text[],
  'Full extension at the back. Slow tempo.'
) on conflict (id) do update set
  name = excluded.name,
  equipment = excluded.equipment,
  type = excluded.type,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  notes = excluded.notes;

insert into public.plan_days (
  id, plan_id, day, type, focus, duration_minutes,
  warmup, cardio_title, cardio_duration_minutes, cardio_instructions
) values (
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  'f889b46e-a829-5c23-b19b-20cf66ed4931'::uuid,
  'Monday',
  'Push',
  'Push — Chest + Shoulders + Triceps',
  80,
  '5 min cross cycling + 2 sets light dumbbell shoulder circles',
  'Treadmill incline walk',
  15,
  '12-15% incline, 5.5 km/h'
) on conflict (plan_id, day) do update set
  type = excluded.type,
  focus = excluded.focus,
  duration_minutes = excluded.duration_minutes,
  warmup = excluded.warmup,
  cardio_title = excluded.cardio_title,
  cardio_duration_minutes = excluded.cardio_duration_minutes,
  cardio_instructions = excluded.cardio_instructions;

insert into public.plan_days (
  id, plan_id, day, type, focus, duration_minutes,
  warmup, cardio_title, cardio_duration_minutes, cardio_instructions
) values (
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  'f889b46e-a829-5c23-b19b-20cf66ed4931'::uuid,
  'Tuesday',
  'Pull',
  'Pull — Back + Biceps',
  80,
  '5 min cycling + band pull-aparts if available',
  'Steady cycling',
  15,
  'Zone 2 pace — conversational (60-65% max HR)'
) on conflict (plan_id, day) do update set
  type = excluded.type,
  focus = excluded.focus,
  duration_minutes = excluded.duration_minutes,
  warmup = excluded.warmup,
  cardio_title = excluded.cardio_title,
  cardio_duration_minutes = excluded.cardio_duration_minutes,
  cardio_instructions = excluded.cardio_instructions;

insert into public.plan_days (
  id, plan_id, day, type, focus, duration_minutes,
  warmup, cardio_title, cardio_duration_minutes, cardio_instructions
) values (
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  'f889b46e-a829-5c23-b19b-20cf66ed4931'::uuid,
  'Wednesday',
  'Legs',
  'Legs — Quad + Glute + Hamstring',
  85,
  '8 min cycling, increasing resistance every 2 min',
  'Treadmill walk',
  10,
  'Flat, easy pace — active recovery only'
) on conflict (plan_id, day) do update set
  type = excluded.type,
  focus = excluded.focus,
  duration_minutes = excluded.duration_minutes,
  warmup = excluded.warmup,
  cardio_title = excluded.cardio_title,
  cardio_duration_minutes = excluded.cardio_duration_minutes,
  cardio_instructions = excluded.cardio_instructions;

insert into public.plan_days (
  id, plan_id, day, type, focus, duration_minutes,
  warmup, cardio_title, cardio_duration_minutes, cardio_instructions
) values (
  '9acc9070-bc6e-530b-be15-1360b808ba6e'::uuid,
  'f889b46e-a829-5c23-b19b-20cf66ed4931'::uuid,
  'Thursday',
  'Core',
  'Core + Cardio + Weak Points',
  65,
  'None — light day',
  'Treadmill LISS-HIIT hybrid',
  25,
  '1 min walk (7 km/h) alternating with 1 min jog (9 km/h)'
) on conflict (plan_id, day) do update set
  type = excluded.type,
  focus = excluded.focus,
  duration_minutes = excluded.duration_minutes,
  warmup = excluded.warmup,
  cardio_title = excluded.cardio_title,
  cardio_duration_minutes = excluded.cardio_duration_minutes,
  cardio_instructions = excluded.cardio_instructions;

insert into public.plan_days (
  id, plan_id, day, type, focus, duration_minutes,
  warmup, cardio_title, cardio_duration_minutes, cardio_instructions
) values (
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  'f889b46e-a829-5c23-b19b-20cf66ed4931'::uuid,
  'Friday',
  'Full Body',
  'Full Body Compound + Strength',
  80,
  '5 min cross cycling + dynamic leg swings',
  'Cross cycling',
  20,
  'Moderate steady-state, conversational pace'
) on conflict (plan_id, day) do update set
  type = excluded.type,
  focus = excluded.focus,
  duration_minutes = excluded.duration_minutes,
  warmup = excluded.warmup,
  cardio_title = excluded.cardio_title,
  cardio_duration_minutes = excluded.cardio_duration_minutes,
  cardio_instructions = excluded.cardio_instructions;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'b1ed86e7-e79f-5af2-84f4-2b0db02990bb'::uuid,
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  '13fff305-1b3c-5592-8068-02ab6e566c19'::uuid,
  1,
  4,
  '8-10'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '98151c03-cdf3-56b2-9a22-c46b02f13401'::uuid,
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  '93fcd3fd-5290-5800-8bcc-c39d8a03575d'::uuid,
  2,
  3,
  '10-12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '6e91d29a-7e91-5158-b30e-943de5e513ef'::uuid,
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  'e3ddcaff-533d-5e10-903f-8be26eda4772'::uuid,
  3,
  3,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'd314effd-490b-582f-a460-b125b2328229'::uuid,
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  '350f9ab3-e54f-5607-9aa5-69d470b75c75'::uuid,
  4,
  4,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '3546a937-a65d-5d26-af10-841b69e6416a'::uuid,
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  '893c6ab3-20ee-577d-a820-d3da50d26b7d'::uuid,
  5,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'eb251f69-fcbd-5a0a-8834-d452d8ebcf92'::uuid,
  '5e9ee83e-f3a7-571a-9550-660102bb4322'::uuid,
  'f2edab83-ce37-5d11-a123-b6993e882909'::uuid,
  6,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '1cf82ff8-e965-5170-b490-eb218317106c'::uuid,
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  '833e4b9a-e5d6-5a59-91e5-10cbea9da999'::uuid,
  1,
  4,
  '8-10'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '1460be3a-fc41-5744-a650-9f64ca4a8550'::uuid,
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  'e5362472-5135-5186-b23e-1fbe56c903a0'::uuid,
  2,
  3,
  'Max or 8'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '3e557c7d-ee8b-54fb-991a-e74adec9dfa2'::uuid,
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  'bdb953c0-f50b-5a17-83c1-0621d7e800d1'::uuid,
  3,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'f8850bb4-6f5f-566e-99b8-b47736c399d3'::uuid,
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  '7d24759e-0b4d-58e7-8c62-0882fdbcde77'::uuid,
  4,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'b01cb9f1-01bc-5087-9d1c-e7cf05558635'::uuid,
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  '49a8bb50-ee5c-58f4-a0ce-68fd8b84d66d'::uuid,
  5,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '8b921697-d4f6-5175-b118-39640bcd8a89'::uuid,
  'c78a8c05-8eee-52fe-b59f-686828ea9f83'::uuid,
  '6d1805f3-11a5-5523-9477-980288e4cca1'::uuid,
  6,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'b6f48af6-a9e4-5f63-b402-273cd65c6aa8'::uuid,
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  'fa090008-e840-5fb3-9069-68cf6cbd24f6'::uuid,
  1,
  4,
  '8-10'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '35e80768-f001-59c4-969c-59aa130ee75c'::uuid,
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  '80832e73-7e2f-5626-bef4-d48bd7e10f0c'::uuid,
  2,
  3,
  '10'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'ddb9dacc-277a-5f51-a192-38a15e60c56f'::uuid,
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  '63ac6a25-3b5c-5ba0-8584-d505ff4e5fd3'::uuid,
  3,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '7b5ecd93-23dd-53c8-b104-7b13792e768c'::uuid,
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  '43789256-efe7-5941-8c94-d9aa225551d6'::uuid,
  4,
  3,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '1f52c951-bbdf-590a-a4a2-613ea5cda815'::uuid,
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  'a2bb7e35-7870-509e-b063-d2f879ec4d65'::uuid,
  5,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '53b714fb-8d95-589c-b6d4-dab65b0eec3a'::uuid,
  '448b292b-cc4e-590c-b2b1-fd4bf797539a'::uuid,
  '66c637ea-103f-53ce-8d63-d186f2924674'::uuid,
  6,
  4,
  '20'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '5e55ca43-2f86-5c76-a8c9-7ef803e1119e'::uuid,
  '9acc9070-bc6e-530b-be15-1360b808ba6e'::uuid,
  'ecf772fb-24ee-593c-b45d-d6a07f86b680'::uuid,
  1,
  4,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '9491dd75-a6bf-50ba-8021-fb938c9849a4'::uuid,
  '9acc9070-bc6e-530b-be15-1360b808ba6e'::uuid,
  'db267787-ecc0-57c6-83eb-81977a39a4f8'::uuid,
  2,
  3,
  '20'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '9a9e4d36-b36c-52be-8be7-ae848d9d3044'::uuid,
  '9acc9070-bc6e-530b-be15-1360b808ba6e'::uuid,
  'f0c4e5ea-88b0-5675-ac8d-5bfba4a48deb'::uuid,
  3,
  3,
  '45-60 seconds'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '34e29adf-db9c-52dd-947b-562955522ac4'::uuid,
  '9acc9070-bc6e-530b-be15-1360b808ba6e'::uuid,
  'caa86797-74a2-59a8-b1d7-b1e97acd2f8c'::uuid,
  4,
  3,
  '20 each side'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '15ee5122-810f-5081-bc06-91c41fd41729'::uuid,
  '9acc9070-bc6e-530b-be15-1360b808ba6e'::uuid,
  '1015ce0b-382e-517a-8014-89f6eef628f3'::uuid,
  5,
  3,
  '20'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '14717cd7-0280-5f0f-8e9d-24bac77cef0a'::uuid,
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  '460df74a-a97a-5df5-9f84-3415da3821c1'::uuid,
  1,
  3,
  '6-8'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'c3a9ec11-556d-5366-a178-187a37578671'::uuid,
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  '4a902087-2e5a-5afd-895b-c2c376d65723'::uuid,
  2,
  3,
  '10'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  'cf66cbcc-c9dd-5a2d-8f99-bc710576e470'::uuid,
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  'd90ffdd1-0018-5cad-8beb-7798032064c6'::uuid,
  3,
  3,
  '12'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '5e0c3f9a-41aa-51ad-b85f-08ada0fcc8a6'::uuid,
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  'ecaf1ca5-e0ec-5332-b66c-c34c5b7d0460'::uuid,
  4,
  3,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '3be16ada-9df8-5bd2-89d4-0cb5007d69da'::uuid,
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  '49a8bb50-ee5c-58f4-a0ce-68fd8b84d66d'::uuid,
  5,
  2,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

insert into public.plan_exercises (id, plan_day_id, exercise_id, sort_order, sets, reps) values (
  '2b919ba8-e4d2-50b8-ba82-b5bdf9280c8d'::uuid,
  'a1537e73-72f9-5d3d-b54a-f9f621cf3e82'::uuid,
  '0d5b115a-cbb6-5194-810a-15f6c039bc1b'::uuid,
  6,
  2,
  '15'
) on conflict (id) do update set
  sort_order = excluded.sort_order,
  sets = excluded.sets,
  reps = excluded.reps;

commit;
