# Project-wide Gradle settings

# Use fixed Node path (important for nvm users)
NODE_BINARY=/usr/local/bin/node
node.executable=/usr/local/bin/node

# JVM config
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m

# Disable daemon (optional but fine for debugging)
org.gradle.daemon=false

# AndroidX
android.useAndroidX=true

# Architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# New architecture
newArchEnabled=true

# Hermes
hermesEnabled=true

# Optional UI setting
edgeToEdgeEnabled=false